[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "opensimrl"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[tool.setuptools]
packages = ["opensimrl"]
