# SAC algorithm configuration
# These map directly to opensimrl.algorithms.sac.sac(...) arguments.

name: sac
seed: 0

# Training schedule
steps_per_epoch: 4000
epochs: 50
max_ep_len: 1000
save_freq: 1

# Replay / updates
replay_size: 1000000
batch_size: 100
start_steps: 10000
update_after: 1000
update_every: 50

# Discounting / targets / optimization
gamma: 0.99
polyak: 0.995
lr: 1e-3
alpha: 0.2

# Evaluation
num_test_episodes: 10

# Actor-critic architecture kwargs
ac_kwargs:
  hidden_sizes: [256, 256]
