# Logger configuration: MLflow (if installed)
# Select with: python -m opensimrl.train logger=mlflow
kind: mlflow
experiment_name: opensimrl
run_name: ppo
# Optional: you can add tracking_uri if using a remote/local server
# tracking_uri: http://localhost:5000
